apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: volodymyrbjj/app-go
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_ENDPOINT
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER
            - name: POSTGRES_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_SCHEMA
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASS
            - name: REDIS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_ENDPOINT
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT
      imagePullSecrets:
        - name: regcred
