services:
  app:
    image: volodymyrbjj/app-go
    restart: always
    tty: true
    build:
      target: prod
      context: .
      dockerfile: Dockerfile
    container_name: app-go
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      SCHEMA: ${POSTGRES_SCHEMA}
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
    external: true



