global:
  resolve_timeout: 5m
route:
  receiver: default
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
receivers:
  - name: default
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/some_url'
        channel: '#alerts'
        username: 'Alertmanager'
        icon_emoji: ':warning:'
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']