services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9000:9000'
    volumes:
      - ./prometheus:/app/monitoring/prometheus
    command:
      - '--config.file=/app/monitoring/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000'
    depends_on:
      - prometheus
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager:/app/monitoring/alertmanager
    command:
      - '--config.file=/app/monitoring/alertmanager/alertmanager.yml'
    restart: always