apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      backend=docker.io/volodymyrbjj/app-go:~1.0,
      frontend=docker.io/volodymyrbjj/app-js:~1.0

    # Map each alias to Helm values (repo + tag fields inside your chart)
    argocd-image-updater.argoproj.io/backend.helm.image-name: backend.image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag
    argocd-image-updater.argoproj.io/frontend.helm.image-name: frontend.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/backend.update-strategy: semver
    argocd-image-updater.argoproj.io/frontend.update-strategy: semver
    argocd-image-updater.argoproj.io/pull-secret: pullsecret:argocd/dockerhub-creds
spec:
  project: default
  source:
    repoURL: https://github.com/voloshyn1992/it-works-on-my-machine.git
    targetRevision: main
    path: charts/webapp
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
