apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  selector:
    app: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.backend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
      {{- if and (eq .Values.backend.service.type "NodePort") (.Values.backend.service.nodePort) }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
